entrada = input("Digite uma string: \n")
entrada = entrada.replace("a", "")
entrada = entrada.replace("e", "")
entrada = entrada.replace("i", "")
entrada = entrada.replace("o", "")
entrada = entrada.replace("u", "")
print(entrada)
